Repository open-edge-platform/app-orch-deployment, pull requests merged in 2025-05, with the labels that each got.

#63 ADM: expand ignoreResources list
  app-deployment-manager/VERSION
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
  app-deployment-manager/pkg/fleet/configgen.go
Labels: run-adm-component-tests

#59 [ITEP-27650] Extend ADM component tests
  .github/workflows/adm-component-test.yml
  .github/workflows/arm-component-test.yml
  .github/workflows/common-comp-tests.yml
  app-deployment-manager/VERSION
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
  app-deployment-manager/test/basic/basic_test.go
  app-deployment-manager/test/basic/create_deployment_test.go
  app-deployment-manager/test/basic/suite_test.go
  app-deployment-manager/test/basic/utils.go
  app-deployment-manager/test/deployment/auth_test.go
  app-deployment-manager/test/deployment/create_deployment_test.go
  app-deployment-manager/test/deployment/methods_test.go
  app-deployment-manager/test/deployment/negative_test.go
  app-deployment-manager/test/deployment/suite_test.go
  app-deployment-manager/test/deployment/utils.go
  app-deployment-manager/test/utils/auth.go
  app-deployment-manager/test/utils/deploy.go
  app-deployment-manager/test/utils/utils.go
  app-interconnect/go.mod
  app-interconnect/go.sum
  app-resource-manager/VERSION
  app-resource-manager/deployments/app-resource-manager/Chart.yaml
  app-resource-manager/test/deploy/utils.go
Labels: run-adm-component-tests

#66 pin orch-ci version in GHA workflows and fix some of the security issues
  .github/workflows/adm-component-test.yml
  .github/workflows/arm-component-test.yml
  .github/workflows/auto-close.yml
  .github/workflows/auto-update.yml
  .github/workflows/common-comp-tests.yml
  .github/workflows/go-fuzz.yml
  .github/workflows/post-merge-adm-nbi.yaml
  .github/workflows/post-merge-adm.yaml
  .github/workflows/post-merge-arm.yaml
  .github/workflows/post-merge-asp.yaml
  .github/workflows/post-merge-interconnect.yaml
  .github/workflows/pre-merge.yml
  app-deployment-manager/README.md
  app-deployment-manager/VERSION
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
Labels: run-adm-component-tests

#75 Fixing component tests
  .github/workflows/adm-component-test.yml
  .github/workflows/arm-component-test.yml
  .github/workflows/common-comp-tests.yml
  .github/workflows/post-merge-adm-nbi.yaml
  .github/workflows/post-merge-adm.yaml
  .github/workflows/post-merge-arm.yaml
  .github/workflows/post-merge-asp.yaml
  .github/workflows/post-merge-interconnect.yaml
Labels: run-adm-component-tests

#62 Update fleet api to 0.12.1
  .github/workflows/adm-component-test.yml
  app-deployment-manager/VERSION
  app-deployment-manager/api/v1beta1/cluster_types.go
  app-deployment-manager/api/v1beta1/deployment_types.go
  app-deployment-manager/api/v1beta1/zz_generated.deepcopy.go
  app-deployment-manager/controllers/cluster/cluster_controller_test.go
  app-deployment-manager/controllers/deployment/deployment_controller.go
  app-deployment-manager/controllers/deployment/deployment_controller_test.go
  app-deployment-manager/controllers/deploymentcluster/deploymentcluster_controller.go
  app-deployment-manager/controllers/deploymentcluster/deploymentcluster_controller_test.go
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
  app-deployment-manager/go.mod
  app-deployment-manager/go.sum
  app-deployment-manager/main.go
  app-deployment-manager/pkg/utils/utils.go
  app-deployment-manager/pkg/utils/utils_test.go
  app-deployment-manager/test/deployment/auth_test.go
  app-interconnect/go.mod
  app-interconnect/go.sum
Labels: run-adm-component-tests

#79 Upgrade EMF branch for ADM and ARM tests
  .github/workflows/adm-component-test.yml
  .github/workflows/arm-component-test.yml
Labels: run-adm-component-tests

#80 Improve ARM component test and enable VM tests
  app-resource-manager/Makefile
  app-resource-manager/test/container/auth_test.go
  app-resource-manager/test/container/endpoint_test.go
  app-resource-manager/test/container/methods_test.go
  app-resource-manager/test/container/suite_test.go
  app-resource-manager/test/container/utils.go
  app-resource-manager/test/utils/auth.go
  app-resource-manager/test/utils/common_types.go
  app-resource-manager/test/utils/deploy.go
  app-resource-manager/test/utils/deploy_utils.go
  app-resource-manager/test/utils/git_clone.go
  app-resource-manager/test/utils/utils.go
  app-resource-manager/test/utils/vm_upload.go
  app-resource-manager/test/vm/auth_test.go
  app-resource-manager/test/vm/endpoint_test.go
  app-resource-manager/test/vm/methods_test.go
  app-resource-manager/test/vm/suite_test.go
  app-resource-manager/test/vm/utils.go
Labels: run-arm-component-tests

#82 ITEP-25679 Have substitution tags for local registry name and Registry Project Name
  app-deployment-manager/VERSION
  app-deployment-manager/controllers/deployment/deployment_controller.go
  app-deployment-manager/controllers/deployment/deployment_controller_test.go
  app-deployment-manager/controllers/deployment/suite_test.go
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
  app-deployment-manager/pkg/fleet/configgen.go
  app-deployment-manager/pkg/fleet/configgen_suite_test.go
  app-deployment-manager/pkg/fleet/configgen_test.go
Labels: run-adm-component-tests

#87 Shorten the bundle name to allow more space for the app deployment name
  app-deployment-manager/VERSION
  app-deployment-manager/controllers/deployment/deployment_controller_test.go
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
  app-deployment-manager/pkg/fleet/configgen.go
Labels: DO_NOT_MERGE, run-adm-component-tests

#92 ITEP-67065 update generation of fleet config in ADM
  app-deployment-manager/VERSION
  app-deployment-manager/api/v1beta1/deployment_types.go
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
  app-deployment-manager/pkg/fleet/configgen.go
  app-deployment-manager/pkg/fleet/configgen_test.go
Labels: run-adm-component-tests

#95 Avoid flipping between no_target cluster/deploying and error states
  app-deployment-manager/VERSION
  app-deployment-manager/controllers/deployment/deployment_controller.go
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
Labels: run-adm-component-tests

#96 Add test report to component tests GHA
  .github/workflows/common-comp-tests.yml
  .gitignore
  app-deployment-manager/VERSION
  app-deployment-manager/deployment/charts/app-deployment-crd/Chart.yaml
  app-deployment-manager/deployment/charts/app-deployment-manager/Chart.yaml
  app-deployment-manager/test/template.html
  app-resource-manager/go.mod
  app-resource-manager/go.sum
  app-resource-manager/test/template.html
  app-resource-manager/test/vm/endpoint_test.go
  common.mk
Labels: run-arm-component-tests

#98 Add ADM tests for GetDeploymentsStatus API endpoint
  app-deployment-manager/test/deployment/auth_test.go
  app-deployment-manager/test/deployment/create_deployment_test.go
  app-deployment-manager/test/deployment/deployment_status_test.go
  app-deployment-manager/test/deployment/methods_test.go
  app-deployment-manager/test/deployment/negative_test.go
  app-deployment-manager/test/deployment/suite_test.go
  app-deployment-manager/test/utils/deploy.go
  app-deployment-manager/test/utils/utils.go
  common.mk
Labels: run-adm-component-tests
